# Licensed under GPL3 (see LICENSE)
# coding=utf-8

"""
Constent for communicating with indiserver via the INDI protocol, http://www.indilib.org.
"""

__authors__ = ("Dominique Touzan","ciboulette module")
__contact__ = ("dtouzan@gmail.com","https://github.com/dtouzan/ciboulette")
__copyright__ = "MIT"
__date__ = "2024-11-02"
__version__= "1.0.0"

list_pylibcamera = ['indi_pylibcamera.CAMERA_SELECTION.CAM0',
                    'indi_pylibcamera.CONNECTION.CONNECT',
                    'indi_pylibcamera.CONNECTION.DISCONNECT',
                    'indi_pylibcamera.DRIVER_INFO.DRIVER_NAME',
                    'indi_pylibcamera.DRIVER_INFO.DRIVER_EXEC',
                    'indi_pylibcamera.DRIVER_INFO.DRIVER_VERSION',
                    'indi_pylibcamera.DRIVER_INFO.DRIVER_INTERFACE',
                    'indi_pylibcamera.LOGGING_LEVEL.LOGGING_DEBUG',
                    'indi_pylibcamera.LOGGING_LEVEL.LOGGING_INFO',
                    'indi_pylibcamera.LOGGING_LEVEL.LOGGING_WARN',
                    'indi_pylibcamera.LOGGING_LEVEL.LOGGING_ERROR',
                    'indi_pylibcamera.POLLING_PERIOD.PERIOD_MS',
                    'indi_pylibcamera.GEOGRAPHIC_COORD.LAT',
                    'indi_pylibcamera.GEOGRAPHIC_COORD.LONG',
                    'indi_pylibcamera.GEOGRAPHIC_COORD.ELEV',
                    'indi_pylibcamera.EQUATORIAL_EOD_COORD.RA',
                    'indi_pylibcamera.EQUATORIAL_EOD_COORD.DEC',
                    'indi_pylibcamera.TELESCOPE_PIER_SIDE.PIER_WEST',
                    'indi_pylibcamera.TELESCOPE_PIER_SIDE.PIER_EAST',
                    'indi_pylibcamera.TELESCOPE_INFO.TELESCOPE_APERTURE',
                    'indi_pylibcamera.TELESCOPE_INFO.TELESCOPE_FOCAL_LENGTH',
                    'indi_pylibcamera.TELESCOPE_INFO.GUIDER_APERTURE',
                    'indi_pylibcamera.TELESCOPE_INFO.GUIDER_FOCAL_LENGTH',
                    'indi_pylibcamera.CAMERA_LENS.PRIMARY_LENS',
                    'indi_pylibcamera.CAMERA_LENS.GUIDER_LENS',
                    'indi_pylibcamera.DO_SNOOPING.SNOOP',
                    'indi_pylibcamera.DO_SNOOPING.NO_SNOOP',
                    'indi_pylibcamera.ACTIVE_DEVICES.ACTIVE_TELESCOPE',
                    'indi_pylibcamera.CAMERA_INFO.CAMERA_MODEL',
                    'indi_pylibcamera.CAMERA_INFO.CAMERA_PIXELARRAYSIZE',
                    'indi_pylibcamera.CAMERA_INFO.CAMERA_PIXELARRAYACTIVEAREA',
                    'indi_pylibcamera.CAMERA_INFO.CAMERA_UNITCELLSIZE',
                    'indi_pylibcamera.CCD_CAPTURE_FORMAT.INDI_RAW',
                    'indi_pylibcamera.CCD_CAPTURE_FORMAT.INDI_RGB',
                    'indi_pylibcamera.RAW_FORMAT.RAWFORMAT0',
                    'indi_pylibcamera.RAW_FORMAT.RAWFORMAT1',
                    'indi_pylibcamera.RAW_FORMAT.RAWFORMAT2',
                    'indi_pylibcamera.RAW_FORMAT.RAWFORMAT3',
                    'indi_pylibcamera.CCD_PROCFRAME.WIDTH',
                    'indi_pylibcamera.CCD_PROCFRAME.HEIGHT',
                    'indi_pylibcamera.CAMCTRL_AEENABLE.INDI_ENABLED',
                    'indi_pylibcamera.CAMCTRL_AEENABLE.INDI_DISABLED',
                    'indi_pylibcamera.CAMCTRL_AECONSTRAINTMODE.NORMAL',
                    'indi_pylibcamera.CAMCTRL_AECONSTRAINTMODE.HIGHLIGHT',
                    'indi_pylibcamera.CAMCTRL_AECONSTRAINTMODE.SHADOWS',
                    'indi_pylibcamera.CAMCTRL_AECONSTRAINTMODE.CUSTOM',
                    'indi_pylibcamera.CAMCTRL_AEEXPOSUREMODE.NORMAL',
                    'indi_pylibcamera.CAMCTRL_AEEXPOSUREMODE.SHORT',
                    'indi_pylibcamera.CAMCTRL_AEEXPOSUREMODE.LONG',
                    'indi_pylibcamera.CAMCTRL_AEEXPOSUREMODE.CUSTOM',
                    'indi_pylibcamera.CAMCTRL_AEMETERINGMODE.CENTREWEIGHTED',
                    'indi_pylibcamera.CAMCTRL_AEMETERINGMODE.SPOT',
                    'indi_pylibcamera.CAMCTRL_AEMETERINGMODE.MATRIX',
                    'indi_pylibcamera.CAMCTRL_AEMETERINGMODE.CUSTOM',
                    'indi_pylibcamera.CAMCTRL_AWBENABLE.INDI_ENABLED',
                    'indi_pylibcamera.CAMCTRL_AWBENABLE.INDI_DISABLED',
                    'indi_pylibcamera.CAMCTRL_AWBMODE.AUTO',
                    'indi_pylibcamera.CAMCTRL_AWBMODE.TUNGSTEN',
                    'indi_pylibcamera.CAMCTRL_AWBMODE.FLUORESCENT',
                    'indi_pylibcamera.CAMCTRL_AWBMODE.INDOOR',
                    'indi_pylibcamera.CAMCTRL_AWBMODE.DAYLIGHT',
                    'indi_pylibcamera.CAMCTRL_AWBMODE.CLOUDY',
                    'indi_pylibcamera.CAMCTRL_AWBMODE.CUSTOM',
                    'indi_pylibcamera.CAMCTRL_BRIGHTNESS.BRIGHTNESS',
                    'indi_pylibcamera.CAMCTRL_COLOURGAINS.REDGAIN',
                    'indi_pylibcamera.CAMCTRL_COLOURGAINS.BLUEGAIN',
                    'indi_pylibcamera.CAMCTRL_CONTRAST.CONTRAST',
                    'indi_pylibcamera.CAMCTRL_EXPOSUREVALUE.EXPOSUREVALUE',
                    'indi_pylibcamera.CAMCTRL_NOISEREDUCTIONMODE.OFF',
                    'indi_pylibcamera.CAMCTRL_NOISEREDUCTIONMODE.FAST',
                    'indi_pylibcamera.CAMCTRL_NOISEREDUCTIONMODE.HIGHQUALITY',
                    'indi_pylibcamera.CAMCTRL_SATURATION.SATURATION',
                    'indi_pylibcamera.CAMCTRL_SHARPNESS.SHARPNESS',
                    'indi_pylibcamera.CCD_EXPOSURE.CCD_EXPOSURE_VALUE',
                    'indi_pylibcamera.CCD_ABORT_EXPOSURE.ABORT',
                    'indi_pylibcamera.CCD_FRAME.X',
                    'indi_pylibcamera.CCD_FRAME.Y',
                    'indi_pylibcamera.CCD_FRAME.WIDTH',
                    'indi_pylibcamera.CCD_FRAME.HEIGHT',
                    'indi_pylibcamera.CCD_BINNING.HOR_BIN',
                    'indi_pylibcamera.CCD_BINNING.VER_BIN',
                    'indi_pylibcamera.CCD_TEMPERATURE.CCD_TEMPERATURE_VALUE',
                    'indi_pylibcamera.CCD_INFO.CCD_MAX_X',
                    'indi_pylibcamera.CCD_INFO.CCD_MAX_Y',
                    'indi_pylibcamera.CCD_INFO.CCD_PIXEL_SIZE',
                    'indi_pylibcamera.CCD_INFO.CCD_PIXEL_SIZE_X',
                    'indi_pylibcamera.CCD_INFO.CCD_PIXEL_SIZE_Y',
                    'indi_pylibcamera.CCD_INFO.CCD_BITSPERPIXEL',
                    'indi_pylibcamera.CCD_COMPRESSION.CCD_COMPRESS',
                    'indi_pylibcamera.CCD_COMPRESSION.CCD_RAW',
                    'indi_pylibcamera.CCD_FRAME_TYPE.FRAME_LIGHT',
                    'indi_pylibcamera.CCD_FRAME_TYPE.FRAME_BIAS',
                    'indi_pylibcamera.CCD_FRAME_TYPE.FRAME_DARK',
                    'indi_pylibcamera.CCD_FRAME_TYPE.FRAME_FLAT',
                    'indi_pylibcamera.UPLOAD_MODE.UPLOAD_CLIENT',
                    'indi_pylibcamera.UPLOAD_MODE.UPLOAD_LOCAL',
                    'indi_pylibcamera.UPLOAD_MODE.UPLOAD_BOTH',
                    'indi_pylibcamera.UPLOAD_SETTINGS.UPLOAD_DIR',
                    'indi_pylibcamera.UPLOAD_SETTINGS.UPLOAD_PREFIX',
                    'indi_pylibcamera.CCD_FAST_TOGGLE.INDI_ENABLED',
                    'indi_pylibcamera.CCD_FAST_TOGGLE.INDI_DISABLED',
                    'indi_pylibcamera.CCD_FAST_COUNT.FRAMES',
                    'indi_pylibcamera.CCD_GAIN.GAIN',
                    'indi_pylibcamera.APPLY_CONFIG.CONFIG1',
                    'indi_pylibcamera.APPLY_CONFIG.CONFIG2',
                    'indi_pylibcamera.APPLY_CONFIG.CONFIG3',
                    'indi_pylibcamera.APPLY_CONFIG.CONFIG4',
                    'indi_pylibcamera.APPLY_CONFIG.CONFIG5',
                    'indi_pylibcamera.APPLY_CONFIG.CONFIG6',
                    'indi_pylibcamera.CONFIG_NAME.CONFIG_NAME',
                    'indi_pylibcamera.CONFIG_PROCESS.CONFIG_LOAD',
                    'indi_pylibcamera.CONFIG_PROCESS.CONFIG_SAVE',
                    'indi_pylibcamera.CONFIG_PROCESS.CONFIG_DEFAULT',
                    'indi_pylibcamera.CONFIG_PROCESS.CONFIG_PURGE',]
